CREATE TABLE KLUBY (
id_klubu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
nazev VARCHAR(50) NOT NULL,
mesto VARCHAR(50) NOT NULL,
stadion VARCHAR(50) NOT NULL,
kapacita_stadionu INTEGER NOT NULL
);

CREATE TABLE HRACI (
id_hrace NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
jmeno VARCHAR(50) NOT NULL,
prijmeni VARCHAR(50) NOT NULL,
narodnost VARCHAR(50)  
);

CREATE TABLE HRAC_PUSOBICI_V_KLUBU (
id_hrace_pusobiciho_v_klubu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
od DATE NOT NULL,
do DATE NOT NULL,
KLUBY_id_klubu INTEGER,
HRACI_id_hrace INTEGER,    
CONSTRAINT HRAC_PUSOBICI_V_KLUBU_KLUBY_FK FOREIGN KEY (KLUBY_id_klubu)
    									  REFERENCES KLUBY (id_klubu) ON DELETE CASCADE,
CONSTRAINT HRAC_PUSOBICI_V_KLUBU_HRACI_FK FOREIGN KEY (HRACI_id_hrace)
    									  REFERENCES HRACI (id_hrace) ON DELETE CASCADE
);

CREATE TABLE ZAPAS (
id_zapasu NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
datum DATE NOT NULL,
cas TIMESTAMP NOT NULL,
misto VARCHAR2(50) NOT NULL,
goly_domaci INTEGER NOT NULL,
goly_hoste INTEGER NOT NULL,
KLUBY_id_klubu INTEGER,
KLUBY_id_klubu2 INTEGER,    
CONSTRAINT ZAPAS_KLUBY_FK FOREIGN KEY (KLUBY_id_klubu)	
    					  REFERENCES KLUBY (id_klubu) ON DELETE CASCADE,
CONSTRAINT ZAPAS_KLUBY_FKv2 FOREIGN KEY (KLUBY_id_klubu2)
    					  REFERENCES KLUBY (id_klubu) ON DELETE CASCADE
);

CREATE TABLE SESTAVA_V_ZAPASE(
id_sestavy NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
prvni_minuta_sestavy_v_zapase INTEGER NOT NULL,
posledni_minuta_sestavy_v_zapase INTEGER NOT NULL,
ZAPAS_id_zapasu	INTEGER,
HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu INTEGER,
CONSTRAINT SESTAVA_V_ZAPASE_ZAPAS_FK FOREIGN KEY (ZAPAS_id_zapasu)
    								 REFERENCES ZAPAS (id_zapasu) ON DELETE CASCADE,
CONSTRAINT SESTAVA_V_ZAPASE_HRAC_PUSOBICI_V_KLUBU_FK FOREIGN KEY (HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu)
    												 REFERENCES HRAC_PUSOBICI_V_KLUBU (id_hrace_pusobiciho_v_klubu)  ON DELETE CASCADE
);

CREATE TABLE UDALOST(
id_udalosti	NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
typ VARCHAR(100) NOT NULL,
minuta INTEGER NOT NULL,
ZAPAS_id_zapasu	INTEGER,
SESTAVA_V_ZAPASE_id_sestavy INTEGER,
CONSTRAINT UDALOST_ZAPAS_FK FOREIGN KEY (ZAPAS_id_zapasu)
    						REFERENCES ZAPAS (id_zapasu) ON DELETE CASCADE,
CONSTRAINT UDALOST_SESTAVA_V_ZAPASE_FK FOREIGN KEY (SESTAVA_V_ZAPASE_id_sestavy)
    								   REFERENCES SESTAVA_V_ZAPASE (id_sestavy) ON DELETE CASCADE
);

CREATE TABLE STATISTIKA (
id_statistiky NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
nazev VARCHAR(50) NOT NULL    
);

CREATE TABLE ZAPAS_STATISTIKA (
zapas_statistika_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
hodnota_domaci INTEGER NOT NULL,
hodnota_hoste INTEGER NOT NULL,    
STATISTIKA_id_statistiky INTEGER,
ZAPAS_id_zapasu INTEGER,
CONSTRAINT ZAPAS_STATISTIKA_STATISTIKA_FK FOREIGN KEY (STATISTIKA_id_statistiky)
    									  REFERENCES STATISTIKA (id_statistiky)  ON DELETE CASCADE,
CONSTRAINT ZAPAS_STATISTIKA_ZAPAS_FK FOREIGN KEY (ZAPAS_id_zapasu)
    							     REFERENCES ZAPAS (id_zapasu) ON DELETE CASCADE      
);


INSERT INTO KLUBY (nazev, mesto, stadion, kapacita_stadionu)
VALUES ('FC Viktoria Plzeň', 'Plzeň', 'Doosan Arena', 11700);
INSERT INTO KLUBY (nazev, mesto, stadion, kapacita_stadionu)
VALUES ('FC Slovácko', 'Uherské Hradiště', 'Městský fotbalový stadion Miroslava Valenty', 8000);
INSERT INTO KLUBY (nazev, mesto, stadion, kapacita_stadionu)
VALUES ('SK Slavia Praha', 'Praha', 'Fortuna Arena', 19370);
INSERT INTO KLUBY (nazev, mesto, stadion, kapacita_stadionu)
VALUES ('AC Sparta Praha', 'Praha', 'epet Arena', 18349);

INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Martin', 'Jedlička', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Viktor', 'Baier', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Marián', 'Tvrdoň', 'Slovenská republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Sampson', 'Dweh', 'Libérie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Lukáš', 'Hejda', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Libor', 'Holík', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Robin', 'Hranáč', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Václav', 'Jemelka', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jan', 'Paluska', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Radim', 'Řezník', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Pavel', 'Bucha', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Lopéz', 'Cadu', 'Brazílie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Erik', 'Jirka', 'Slovenská republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Lukáš', 'Kalvach', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jan', 'Kopic', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('John', 'Mosquera', 'Kolumbie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jan', 'Sýkora', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Ibrahim', 'Traoré', 'Pobřeží Slonoviny');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Pavel', 'Šulc', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Tomáš', 'Chorý', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Rafiu', 'Durosinmi', 'Nigérie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jan', 'Kliment', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Matěj', 'Vydra', 'Česká republika');

INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Peter', 'Vindahl', 'Norsko');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Vojtěch', 'Vorel', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('James', 'Gomez', 'Gambie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jan', 'Mejdr', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Filip', 'Panák', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Angelo', 'Preciádo', 'Ekvádor');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Asger', 'Sorensen', 'Norsko');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Martin', 'Vitík', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Patrik', 'Vydra', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Tomáš', 'Wiesner', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jaroslav', 'Zelený', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Veljko', 'Birmančevič', 'Srbsko');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Lukáš', 'Haraslín', 'Slovenská republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Kaan', 'Kairinen', 'Finsko');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Adam', 'Karabec', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Ladislav', 'Krejčí', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Qazim', 'Laci', 'Albánie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('David', 'Pavelka', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jakub', 'Pešek', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Ryneš', 'Matěj', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Lukáš', 'Sadílek', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Michal', 'Ševčík', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jan', 'Kuchta', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Victor', 'Olatunji', 'Nigérie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Václav', 'Sejk', 'Česká republika');

INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jindřich', 'Staněk', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Ondřej', 'Kolář', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Aleš', 'Mandous', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jan', 'Bořil', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Oscar', 'Dorley', 'Libérie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Andres', 'dumitrescu', 'Belgie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Taras', 'Kacharaba', 'Ukrajina');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Igoch', 'Ogbu', 'Nigérie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Alham', 'Ousou', 'Sýrie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Sinyan', 'Sheriff', 'Gambie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Michal', 'Tomič', 'Slovenská republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Vlček', 'Tomáš', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('David', 'Douděra', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Tomáš', 'Holeš', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jakub', 'Hromada', 'Slovenská republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Matěj', 'Jurásek', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Lukáš', 'Masopust', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Lukáš', 'Provod', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Conrad', 'Wallem', 'Norsko');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Christos', 'Zafeiris', 'Norsko');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Petr', 'Ševčík', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Mojmír', 'Chytil', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Václav', 'Jurečka', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Ivan', 'Schranz', 'Slovenská republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Stanislav', 'Tecl', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Muhamed', 'Tijani', 'Nigérie');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Mick', 'van Buren', 'Nizozemsko');

INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Tomáš', 'Fryšták', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Milan', 'Heča', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Stanislav', 'Hofmannn', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Michal', 'Kadlec', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Petr', 'Reinberk', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jaromír', 'Srubek', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Daníček', 'Vlastimil', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Merchas', 'Doski', 'Irák');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Marek', 'Havlík', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Daniel', 'Holzer', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Pavel', 'Juroška', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Jan', 'Kalabiška', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Seung-Bin', 'Kim', 'Jižní korea');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Michal', 'Kohút', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Milan', 'Petržela', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Vlasly', 'Sinyavskiy', 'Estonsko');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Michal', 'Trávník', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Patrik', 'Brandner', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Rigino', 'Cicilia', 'Curacao');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Ondřej', 'Mihálik', 'Česká republika');
INSERT INTO HRACI (jmeno, prijmeni, narodnost)
VALUES ('Filip', 'Vecheta', 'Česká republika');

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-01-07', 'YYYY-MM-DD'), TO_DATE('2026-01-07', 'YYYY-MM-DD'), 1, 1);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-01-07', 'YYYY-MM-DD'), TO_DATE('2026-01-07', 'YYYY-MM-DD'), 1, 2);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2023-07-20', 'YYYY-MM-DD'), TO_DATE('2025-07-20', 'YYYY-MM-DD'), 1, 3);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2016-07-27', 'YYYY-MM-DD'), TO_DATE('2024-07-27', 'YYYY-MM-DD'), 1, 4);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-01-07', 'YYYY-MM-DD'), TO_DATE('2026-01-07', 'YYYY-MM-DD'), 1, 5);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2021-01-10', 'YYYY-MM-DD'), TO_DATE('2026-01-10', 'YYYY-MM-DD'), 1, 6);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-01-12', 'YYYY-MM-DD'), TO_DATE('2027-01-12', 'YYYY-MM-DD'), 1, 7);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2023-07-15', 'YYYY-MM-DD'), TO_DATE('2026-07-15', 'YYYY-MM-DD'), 1, 8);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2015-07-14', 'YYYY-MM-DD'), TO_DATE('2026-07-14', 'YYYY-MM-DD'), 1, 9);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2020-07-07', 'YYYY-MM-DD'), TO_DATE('2027-07-07', 'YYYY-MM-DD'), 1, 10);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-07-15', 'YYYY-MM-DD'), TO_DATE('2027-07-15', 'YYYY-MM-DD'), 1, 11);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2020-07-08', 'YYYY-MM-DD'), TO_DATE('2029-07-08', 'YYYY-MM-DD'), 1, 12);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2014-01-12', 'YYYY-MM-DD'), TO_DATE('2025-01-12', 'YYYY-MM-DD'), 1, 13);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-01-05', 'YYYY-MM-DD'), TO_DATE('2026-01-05', 'YYYY-MM-DD'), 1, 14);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-01-08', 'YYYY-MM-DD'), TO_DATE('2028-01-08', 'YYYY-MM-DD'), 1, 15);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2023-07-25', 'YYYY-MM-DD'), TO_DATE('2026-07-25', 'YYYY-MM-DD'), 1, 16);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-07-14', 'YYYY-MM-DD'), TO_DATE('2029-07-14', 'YYYY-MM-DD'), 1, 17);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2019-01-04', 'YYYY-MM-DD'), TO_DATE('2025-01-04', 'YYYY-MM-DD'), 1, 18);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2023-01-07', 'YYYY-MM-DD'), TO_DATE('2027-01-07', 'YYYY-MM-DD'), 1, 19);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2021-01-05', 'YYYY-MM-DD'), TO_DATE('2026-01-05', 'YYYY-MM-DD'), 1, 20);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-01-21', 'YYYY-MM-DD'), TO_DATE('2026-01-21', 'YYYY-MM-DD'), 1, 21);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2021-01-05', 'YYYY-MM-DD'), TO_DATE('2027-01-05', 'YYYY-MM-DD'), 1, 22);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace) 
VALUES (TO_DATE('2022-01-21', 'YYYY-MM-DD'), TO_DATE('2026-01-21', 'YYYY-MM-DD'), 1, 23);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2016-07-01', 'YYYY-MM-DD'), TO_DATE('2029-07-01', 'YYYY-MM-DD'), 4, 24);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2017-01-07', 'YYYY-MM-DD'), TO_DATE('2028-01-07', 'YYYY-MM-DD'), 4, 25);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2018-07-01', 'YYYY-MM-DD'), TO_DATE('2027-07-01', 'YYYY-MM-DD'), 4, 26);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2019-01-07', 'YYYY-MM-DD'), TO_DATE('2026-01-07', 'YYYY-MM-DD'), 4, 27);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-07-01', 'YYYY-MM-DD'), TO_DATE('2025-07-01', 'YYYY-MM-DD'), 4, 28);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-01-07', 'YYYY-MM-DD'), TO_DATE('2025-01-07', 'YYYY-MM-DD'), 4, 29);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2025-07-01', 'YYYY-MM-DD'), 4, 30);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2026-01-01', 'YYYY-MM-DD'), 4, 31);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-07-07', 'YYYY-MM-DD'), TO_DATE('2028-07-07', 'YYYY-MM-DD'), 4, 32);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-01', 'YYYY-MM-DD'), 4, 33);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2029-07-07', 'YYYY-MM-DD'), 4, 34);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2026-01-01', 'YYYY-MM-DD'), 4, 35);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2029-07-07', 'YYYY-MM-DD'), 4, 36);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2029-01-01', 'YYYY-MM-DD'), 4, 37);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2026-07-07', 'YYYY-MM-DD'), 4, 38);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-01', 'YYYY-MM-DD'), 4, 39);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2028-07-07', 'YYYY-MM-DD'), 4, 40);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2025-01-01', 'YYYY-MM-DD'), 4, 41);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2016-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-01', 'YYYY-MM-DD'), 4, 42);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-07-01', 'YYYY-MM-DD'), TO_DATE('2029-07-01', 'YYYY-MM-DD'), 4, 43);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2014-01-01', 'YYYY-MM-DD'), TO_DATE('2025-01-01', 'YYYY-MM-DD'), 4, 44);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2026-01-01', 'YYYY-MM-DD'), 4, 45);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2028-07-07', 'YYYY-MM-DD'), 4, 46);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-01', 'YYYY-MM-DD'), 4, 47);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2024-07-07', 'YYYY-MM-DD'), TO_DATE('2029-07-07', 'YYYY-MM-DD'), 4, 48);

INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2016-07-01', 'YYYY-MM-DD'), TO_DATE('2029-07-01', 'YYYY-MM-DD'), 3, 49);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2017-01-07', 'YYYY-MM-DD'), TO_DATE('2028-01-07', 'YYYY-MM-DD'), 3, 50);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2018-07-01', 'YYYY-MM-DD'), TO_DATE('2027-07-01', 'YYYY-MM-DD'), 3, 51);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2019-01-07', 'YYYY-MM-DD'), TO_DATE('2026-01-07', 'YYYY-MM-DD'), 3, 52);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-07-01', 'YYYY-MM-DD'), TO_DATE('2025-07-01', 'YYYY-MM-DD'), 3, 53);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-01-07', 'YYYY-MM-DD'), TO_DATE('2025-01-07', 'YYYY-MM-DD'), 3, 54);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-01', 'YYYY-MM-DD'), 3, 55);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2026-01-01', 'YYYY-MM-DD'), 3, 56);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2024-07-07', 'YYYY-MM-DD'), TO_DATE('2028-07-07', 'YYYY-MM-DD'), 3, 57);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-01', 'YYYY-MM-DD'), 3, 58);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-07-07', 'YYYY-MM-DD'), TO_DATE('2029-07-07', 'YYYY-MM-DD'), 3, 59);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-01-01', 'YYYY-MM-DD'), TO_DATE('2026-01-01', 'YYYY-MM-DD'), 3, 60);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2024-07-07', 'YYYY-MM-DD'), TO_DATE('2029-07-07', 'YYYY-MM-DD'), 3, 61);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2029-01-01', 'YYYY-MM-DD'), 3, 62);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2026-07-07', 'YYYY-MM-DD'), 3, 63);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-01', 'YYYY-MM-DD'), 3, 64);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2028-07-07', 'YYYY-MM-DD'), 3, 65);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2025-01-01', 'YYYY-MM-DD'), 3, 66);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2016-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-01', 'YYYY-MM-DD'), 3, 67);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-07-01', 'YYYY-MM-DD'), TO_DATE('2029-07-01', 'YYYY-MM-DD'), 3, 68);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2014-01-01', 'YYYY-MM-DD'), TO_DATE('2025-01-01', 'YYYY-MM-DD'), 3, 69);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2026-01-01', 'YYYY-MM-DD'), 3, 70);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2028-07-07', 'YYYY-MM-DD'), 3, 71);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-01', 'YYYY-MM-DD'), 3, 72);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-07-07', 'YYYY-MM-DD'), TO_DATE('2029-07-07', 'YYYY-MM-DD'), 3, 73);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-01', 'YYYY-MM-DD'), 3, 74);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-07-07', 'YYYY-MM-DD'), TO_DATE('2028-07-07', 'YYYY-MM-DD'), 3, 75);



INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2016-07-01', 'YYYY-MM-DD'), TO_DATE('2029-07-01', 'YYYY-MM-DD'), 2, 76);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2017-01-07', 'YYYY-MM-DD'), TO_DATE('2028-01-07', 'YYYY-MM-DD'), 2, 77);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2018-07-01', 'YYYY-MM-DD'), TO_DATE('2027-07-01', 'YYYY-MM-DD'), 2, 78);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2019-01-07', 'YYYY-MM-DD'), TO_DATE('2026-01-07', 'YYYY-MM-DD'), 2, 79);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-07-01', 'YYYY-MM-DD'), TO_DATE('2025-07-01', 'YYYY-MM-DD'), 2, 80);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-01-07', 'YYYY-MM-DD'), TO_DATE('2025-01-07', 'YYYY-MM-DD'), 2, 81);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-01', 'YYYY-MM-DD'), TO_DATE('2025-07-01', 'YYYY-MM-DD'), 2, 82);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2026-01-01', 'YYYY-MM-DD'), 2, 83);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-07-07', 'YYYY-MM-DD'), TO_DATE('2028-07-07', 'YYYY-MM-DD'), 2, 84);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-01', 'YYYY-MM-DD'), 2, 85);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-07-07', 'YYYY-MM-DD'), TO_DATE('2029-07-07', 'YYYY-MM-DD'), 2, 86);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-01-01', 'YYYY-MM-DD'), TO_DATE('2026-01-01', 'YYYY-MM-DD'), 2, 87);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-07-07', 'YYYY-MM-DD'), TO_DATE('2029-07-07', 'YYYY-MM-DD'), 2, 88);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-01-01', 'YYYY-MM-DD'), TO_DATE('2029-01-01', 'YYYY-MM-DD'), 2, 89);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2026-07-07', 'YYYY-MM-DD'), 2, 90);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2021-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-01', 'YYYY-MM-DD'), 2, 91);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2022-07-07', 'YYYY-MM-DD'), TO_DATE('2028-07-07', 'YYYY-MM-DD'), 2, 92);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2025-01-01', 'YYYY-MM-DD'), 2, 93);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2016-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-01', 'YYYY-MM-DD'), 2, 94);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2020-07-01', 'YYYY-MM-DD'), TO_DATE('2029-07-01', 'YYYY-MM-DD'), 2, 95);
INSERT INTO HRAC_PUSOBICI_V_KLUBU (od, do, KLUBY_id_klubu, HRACI_id_hrace)
VALUES 
(TO_DATE('2014-01-01', 'YYYY-MM-DD'), TO_DATE('2025-01-01', 'YYYY-MM-DD'), 2, 96);


INSERT INTO STATISTIKA (nazev)
VALUES ('Držení míče');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Střely celkem');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Střely na branku');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Střely mimo branku');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Zablokované střely');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Příme kopy');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Rohové kopy');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Ofsajdy');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Vhazování');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Zásahy brankařů');
INSERT INTO STATISTIKA (nazev)
VALUES 
('fauly');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Žluté karty');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Útoky');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Nebezpečné útoky');
INSERT INTO STATISTIKA (nazev)
VALUES 
('Držení míče');

INSERT INTO ZAPAS (datum, cas, misto, goly_domaci, goly_hoste, KLUBY_id_klubu, KLUBY_id_klubu2)
VALUES (TO_DATE('2023-11-05', 'YYYY-MM-DD'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 'Fortuna Arena (Praha)', 1, 2, 3, 1);

INSERT INTO ZAPAS (datum, cas, misto, goly_domaci, goly_hoste, KLUBY_id_klubu, KLUBY_id_klubu2)
VALUES (TO_DATE('2023-09-17', 'YYYY-MM-DD'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 'Městský stadion (Uherské Hradiště)', 0, 5, 2, 4);

INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES (0, 98, 1, 1);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES (0, 98, 1, 7);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 8);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 15);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 14);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 18);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 12);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 93, 1, 13);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 61, 1, 19);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(61, 89, 1, 23);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(89, 98, 1, 17);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(93, 98, 1, 5);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 20);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 4);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 51);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 57);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 56);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 72, 1, 52);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(72, 98, 1, 58);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(83, 98, 1, 65);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 59);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 68);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 53);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 66);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 98, 1, 67);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES (0, 62, 1, 75);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(62, 98, 1, 74);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(62, 72, 1, 64);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 62, 1, 70);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(72, 98, 1, 71);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES (0, 94, 2, 77);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 79);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 80);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 79, 2, 81);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(79, 94, 2, 87);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 83);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 92);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 84);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 91);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 35, 2, 95);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 68, 2, 85);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 79, 2, 96);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(79, 94, 2, 94);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(68, 94, 2, 86);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(35, 94, 2, 88);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 24);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 61, 2, 30);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(61, 94, 2, 31);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 28);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 39);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 71, 2, 33);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(71, 94, 2, 29);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 44);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 61, 2, 37);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(61, 94, 2, 40);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 43);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 35);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 36);
INSERT INTO SESTAVA_V_ZAPASE (prvni_minuta_sestavy_v_zapase, posledni_minuta_sestavy_v_zapase, ZAPAS_id_zapasu, HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu) 	
VALUES 
(0, 94, 2, 46);



INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES ('Gól !!! na 1:0', 13, 1, 26);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Žlutá karta (podražení)', 51, 1, 5);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Žlutá karta (podražení)', 51, 1, 6);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Žlutá karta (podražení)', 57, 1, 18);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 61, 1, 9);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 61, 1, 10);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 62, 1, 29);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 62, 1, 27);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 62, 1, 26);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 62, 1, 28);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Gól !!! na 1:1', 64, 1, 8);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 72, 1, 28);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 72, 1, 30);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 72, 1, 18);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 72, 1, 19);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Gól !!! na 1:2', 79, 1, 8);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 83, 1, 21);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 83, 1, 20);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 89, 1, 10);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 89, 1, 11);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Žlutá karta (zdržování hry)', 92, 1, 14);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 93, 1, 8);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 93, 1, 12);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES ('Gól !!! na 0:1', 11, 2, 57);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Gól !!! na 0:2', 20, 2, 51);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 35, 2, 40);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 35, 2, 45);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Gól !!! na 0:3', 46, 2, 58);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Žlutá karta (faul)', 46, 2, 42);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 61, 2, 47);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 61, 2, 48);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 61, 2, 54);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 61, 2, 55);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 68, 2, 41);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 68, 2, 46);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Gól !!! na 0:4', 70, 2, 57);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 71, 2, 51);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 71, 2, 52);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 79, 2, 42);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 79, 2, 43);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střidání (ze hřiště)', 79, 2, 34);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Střídání (na hřiště)', 79, 2, 35);
INSERT INTO UDALOST (typ, minuta, ZAPAS_id_zapasu, SESTAVA_V_ZAPASE_id_sestavy)
VALUES
('Gól !!! na 0:5', 81, 2, 59);



INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES (57, 43, 1, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(7, 10, 2, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(2, 3, 3, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(3, 5, 4, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(2, 2, 5, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(14, 13, 6, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(1, 3, 7, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(0, 2, 8, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(41, 23, 9, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(1, 1, 10, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(13, 12, 11, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(3, 6, 12, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(111, 107, 13, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(58, 59, 14, 1);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(39, 61, 1, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(7, 16, 2, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(3, 9, 3, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(2, 4, 4, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(2, 23, 5, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(18, 7, 6, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(4, 3, 7, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(0, 5, 8, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(21, 18, 9, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(4, 3, 10, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(13, 7, 11, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(2, 0, 12, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(86, 80, 13, 2);

INSERT INTO ZAPAS_STATISTIKA (hodnota_domaci, hodnota_hoste, STATISTIKA_id_statistiky, ZAPAS_id_zapasu)
VALUES 
(39, 53, 14, 2);


CREATE VIEW cizinci_v_zapasech AS 
SELECT k.nazev, h.jmeno, h.prijmeni, h.narodnost, s.prvni_minuta_sestavy_v_zapase, s.posledni_minuta_sestavy_v_zapase, z.datum
	FROM HRACI h, SESTAVA_V_ZAPASE s, ZAPAS z, HRAC_PUSOBICI_V_KLUBU hp, KLUBY k
WHERE hp.id_hrace_pusobiciho_v_klubu = s.HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu AND s.ZAPAS_id_zapasu = z.id_zapasu AND hp.HRACI_id_hrace = h.id_hrace AND h.narodnost != 'Česká republika' AND hp.KLUBY_id_klubu = k.id_klubu;


CREATE VIEW tabulka_strelcu AS 
SELECT k.nazev, hr.jmeno, hr.prijmeni, COUNT(u.typ) AS pocet_golu
	FROM KLUBY k, HRAC_PUSOBICI_V_KLUBU h, UDALOST u, SESTAVA_V_ZAPASE s, HRACI hr 
WHERE u.SESTAVA_V_ZAPASE_id_sestavy = s.id_sestavy AND h.id_hrace_pusobiciho_v_klubu = s.HRAC_PUSOBICI_V_KLUBU_id_hrace_pusobiciho_v_klubu AND  hr.id_hrace = h.id_hrace_pusobiciho_v_klubu AND k.id_klubu = h.KLUBY_id_klubu AND u.typ LIKE 'Gól%'
GROUP BY hr.id_hrace, k.nazev, hr.jmeno, hr.prijmeni
ORDER BY pocet_golu DESC;
